// Copyright [2026] [International Union of Railways (UIC)]
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//        http://www.apache.org/licenses/LICENSE-2.0

'use strict';

/**
 * alertmanagerConfig.test.js — unit tests for the v1.9.0 alerting templater
 *
 * Covers the four exports of src/utils/alertmanagerConfig.js:
 *   1. renderConfig()  — pure YAML templating from DB values
 *   2. writeConfig()   — fs interaction (idempotent, creates parent dirs)
 *   3. reload()        — POST /-/reload via Node fetch (mocked)
 *   4. applyConfig()   — orchestrator combining the above
 *
 * Uses real DB writes via the shared test SQLite (the `getConfig` chain is
 * the easiest way to seed values without mocking Node's require cache).
 */

const fs   = require('fs');
const path = require('path');
const os   = require('os');

const { run } = require('../../src/db/db');
const am = require('../../src/utils/alertmanagerConfig');

// Tiny helper: set or replace a server_config row (mirrors what the admin
// PATCH endpoint does — bypasses the API layer for test simplicity).
function setConfig(key, value) {
  run(
    `INSERT INTO server_config (key, value, updated_at, updated_by)
     VALUES (?, ?, datetime('now'), 'test')
     ON CONFLICT(key) DO UPDATE SET value = excluded.value`,
    [key, String(value)]
  );
}

function clearConfig(key) {
  run('DELETE FROM server_config WHERE key = ?', [key]);
}

// Restore fetch + fs.writeFileSync after each test so mocks don't leak.
let origFetch;
beforeEach(() => { origFetch = global.fetch; });
afterEach(() => { global.fetch = origFetch; jest.restoreAllMocks(); });

describe('renderConfig — happy path', () => {
  beforeEach(() => {
    setConfig('SMTP_HOST',    'smtp-relay.brevo.com');
    setConfig('SMTP_PORT',    '587');
    setConfig('SMTP_USER',    'user@smtp-brevo.com');
    setConfig('SMTP_PASS',    'xsmtpsib-secret');
    setConfig('SMTP_FROM',    'OSCAR Alerts <noreply@example.org>');
    setConfig('SMTP_SECURE',  'false');
    setConfig('ALERT_RECIPIENTS',      'admin1@example.org, admin2@example.org');
    setConfig('ALERT_REPEAT_CRITICAL', '1h');
    setConfig('ALERT_REPEAT_WARNING',  '4h');
  });

  test('returns a YAML string with the expected sections', () => {
    const yaml = am.renderConfig();
    expect(typeof yaml).toBe('string');
    expect(yaml).toMatch(/^global:/m);
    expect(yaml).toMatch(/^route:/m);
    expect(yaml).toMatch(/^receivers:/m);
    expect(yaml).toMatch(/^inhibit_rules:/m);
  });

  test('embeds smarthost as host:port', () => {
    expect(am.renderConfig()).toContain("'smtp-relay.brevo.com:587'");
  });

  test('embeds the From address verbatim', () => {
    expect(am.renderConfig()).toContain("'OSCAR Alerts <noreply@example.org>'");
  });

  test('embeds the SMTP login + password', () => {
    const yaml = am.renderConfig();
    expect(yaml).toContain("'user@smtp-brevo.com'");
    expect(yaml).toContain("'xsmtpsib-secret'");
  });

  test('joins recipients with comma in a single to: field (not multiple entries)', () => {
    const yaml = am.renderConfig();
    expect(yaml).toContain("'admin1@example.org, admin2@example.org'");
    // Exactly one `- to:` line (the recipient list is comma-joined, not
    // multiple list items)
    const toLines = yaml.match(/^\s*- to:/gm) || [];
    expect(toLines).toHaveLength(1);
  });

  test('repeat_interval honors ALERT_REPEAT_CRITICAL and ALERT_REPEAT_WARNING', () => {
    const yaml = am.renderConfig();
    expect(yaml).toContain("repeat_interval: '4h'");   // top-level (warning)
    expect(yaml).toContain("repeat_interval: '1h'");   // nested (critical)
  });

  test('SMTP_SECURE=true → smtp_require_tls: false (port 465 implicit-TLS path)', () => {
    setConfig('SMTP_SECURE', 'true');
    expect(am.renderConfig()).toMatch(/smtp_require_tls:\s+false/);
  });

  test('SMTP_SECURE=false → smtp_require_tls: true (STARTTLS on 587)', () => {
    setConfig('SMTP_SECURE', 'false');
    expect(am.renderConfig()).toMatch(/smtp_require_tls:\s+true/);
  });

  test('embeds the auto-generated header banner', () => {
    expect(am.renderConfig()).toMatch(/^# Auto-generated by OSCAR/m);
  });

  test('inhibit rule suppresses warnings when OscarServerDown fires', () => {
    const yaml = am.renderConfig();
    expect(yaml).toContain('alertname = "OscarServerDown"');
    expect(yaml).toContain('severity = "warning"');
  });
});

describe('renderConfig — input cleanup', () => {
  beforeEach(() => {
    setConfig('SMTP_HOST',    'smtp.example.org');
    setConfig('SMTP_FROM',    'noreply@example.org');
    setConfig('SMTP_USER',    'u');
    setConfig('SMTP_PASS',    'p');
  });

  test('newline-separated recipients are accepted (not just commas)', () => {
    setConfig('ALERT_RECIPIENTS', 'a@x.com\nb@x.com\nc@x.com');
    const yaml = am.renderConfig();
    expect(yaml).toContain('a@x.com, b@x.com, c@x.com');
  });

  test('semicolon-separated recipients are accepted', () => {
    setConfig('ALERT_RECIPIENTS', 'a@x.com; b@x.com');
    expect(am.renderConfig()).toContain('a@x.com, b@x.com');
  });

  test('whitespace and empty entries are stripped', () => {
    setConfig('ALERT_RECIPIENTS', '  a@x.com ,  , ,b@x.com  ');
    expect(am.renderConfig()).toContain('a@x.com, b@x.com');
  });

  test('single-quote in From address is properly YAML-escaped (doubled)', () => {
    setConfig('SMTP_FROM',       "Bob's Alerts <bob@example.org>");
    setConfig('ALERT_RECIPIENTS', 'a@x.com');
    const yaml = am.renderConfig();
    // YAML 1.2 single-quoted scalar escapes ' as ''
    expect(yaml).toContain("'Bob''s Alerts <bob@example.org>'");
  });
});

describe('renderConfig — error paths', () => {
  test('throws when SMTP_HOST is empty', () => {
    setConfig('SMTP_HOST', '');
    setConfig('ALERT_RECIPIENTS', 'a@x.com');
    expect(() => am.renderConfig()).toThrow(/SMTP_HOST is empty/);
  });

  test('throws when ALERT_RECIPIENTS is empty', () => {
    setConfig('SMTP_HOST', 'smtp.example.org');
    setConfig('ALERT_RECIPIENTS', '');
    expect(() => am.renderConfig()).toThrow(/ALERT_RECIPIENTS is empty/);
  });

  test('throws when ALERT_RECIPIENTS is whitespace-only', () => {
    setConfig('SMTP_HOST', 'smtp.example.org');
    setConfig('ALERT_RECIPIENTS', '   ,  ,  ');
    expect(() => am.renderConfig()).toThrow(/ALERT_RECIPIENTS is empty/);
  });
});

describe('writeConfig', () => {
  test('writes the YAML to the configured path', () => {
    const writeSpy = jest.spyOn(fs, 'writeFileSync').mockImplementation(() => {});
    const existsSpy = jest.spyOn(fs, 'existsSync').mockReturnValue(true);
    am.writeConfig('hello: world\n');
    expect(writeSpy).toHaveBeenCalledTimes(1);
    expect(writeSpy.mock.calls[0][0]).toBe(am.CONFIG_PATH);
    expect(writeSpy.mock.calls[0][1]).toBe('hello: world\n');
    expect(existsSpy).toHaveBeenCalled();
  });

  test('creates the parent directory when it does not exist', () => {
    jest.spyOn(fs, 'writeFileSync').mockImplementation(() => {});
    jest.spyOn(fs, 'existsSync').mockReturnValue(false);
    const mkdirSpy = jest.spyOn(fs, 'mkdirSync').mockImplementation(() => {});
    am.writeConfig('payload');
    expect(mkdirSpy).toHaveBeenCalledWith(path.dirname(am.CONFIG_PATH), { recursive: true });
  });

  test('propagates write errors (e.g. permission denied)', () => {
    jest.spyOn(fs, 'existsSync').mockReturnValue(true);
    jest.spyOn(fs, 'writeFileSync').mockImplementation(() => {
      const err = new Error('EACCES: permission denied');
      err.code = 'EACCES';
      throw err;
    });
    expect(() => am.writeConfig('x')).toThrow(/permission denied/);
  });
});

describe('reload — POST /-/reload', () => {
  test('returns ok=true on 200 OK', async () => {
    global.fetch = jest.fn().mockResolvedValue({
      ok: true, status: 200, text: async () => ''
    });
    const r = await am.reload();
    expect(r.ok).toBe(true);
    expect(r.status).toBe(200);
    expect(global.fetch).toHaveBeenCalledWith(am.RELOAD_URL, expect.objectContaining({ method: 'POST' }));
  });

  test('returns ok=false on non-2xx', async () => {
    global.fetch = jest.fn().mockResolvedValue({
      ok: false, status: 500, text: async () => 'internal error'
    });
    const r = await am.reload();
    expect(r.ok).toBe(false);
    expect(r.status).toBe(500);
    expect(r.body).toBe('internal error');
  });

  test('returns ok=false (status 0) on network error — never throws', async () => {
    global.fetch = jest.fn().mockRejectedValue(new Error('ECONNREFUSED'));
    const r = await am.reload();
    expect(r.ok).toBe(false);
    expect(r.status).toBe(0);
    expect(r.body).toContain('ECONNREFUSED');
  });
});

describe('applyConfig — orchestration', () => {
  beforeEach(() => {
    setConfig('SMTP_HOST',         'smtp.example.org');
    setConfig('SMTP_USER',         'u');
    setConfig('SMTP_PASS',         'p');
    setConfig('SMTP_FROM',         'noreply@example.org');
    setConfig('ALERT_RECIPIENTS',  'admin@example.org');
  });

  test('full success → ok=true, written=true, reloaded=true', async () => {
    jest.spyOn(fs, 'existsSync').mockReturnValue(true);
    jest.spyOn(fs, 'writeFileSync').mockImplementation(() => {});
    global.fetch = jest.fn().mockResolvedValue({
      ok: true, status: 200, text: async () => ''
    });
    const r = await am.applyConfig();
    expect(r.ok).toBe(true);
    expect(r.written).toBe(true);
    expect(r.reloaded).toBe(true);
    expect(r.error).toBeNull();
  });

  test('write succeeds, reload fails → ok=false but written=true (file is in place)', async () => {
    jest.spyOn(fs, 'existsSync').mockReturnValue(true);
    jest.spyOn(fs, 'writeFileSync').mockImplementation(() => {});
    global.fetch = jest.fn().mockResolvedValue({
      ok: false, status: 503, text: async () => 'service unavailable'
    });
    const r = await am.applyConfig();
    expect(r.ok).toBe(false);
    expect(r.written).toBe(true);
    expect(r.reloaded).toBe(false);
    expect(r.reloadStatus).toBe(503);
    expect(r.error).toMatch(/Wrote .* but Alertmanager reload .* returned 503/);
  });

  test('render fails (missing config) → ok=false, written=false, error surfaces the reason', async () => {
    clearConfig('SMTP_HOST');
    setConfig('SMTP_HOST', '');
    const r = await am.applyConfig();
    expect(r.ok).toBe(false);
    expect(r.written).toBe(false);
    expect(r.reloaded).toBe(false);
    expect(r.error).toMatch(/SMTP_HOST is empty/);
  });

  test('write fails (e.g. read-only volume) → ok=false, written=false, surfaces fs error', async () => {
    jest.spyOn(fs, 'existsSync').mockReturnValue(true);
    jest.spyOn(fs, 'writeFileSync').mockImplementation(() => {
      throw new Error('EROFS: read-only file system');
    });
    const r = await am.applyConfig();
    expect(r.ok).toBe(false);
    expect(r.written).toBe(false);
    expect(r.error).toMatch(/Could not write/);
    expect(r.error).toMatch(/EROFS/);
  });

  test('result includes configPath and reloadUrl for UI surfacing', async () => {
    jest.spyOn(fs, 'existsSync').mockReturnValue(true);
    jest.spyOn(fs, 'writeFileSync').mockImplementation(() => {});
    global.fetch = jest.fn().mockResolvedValue({ ok: true, status: 200, text: async () => '' });
    const r = await am.applyConfig();
    expect(r.configPath).toBe(am.CONFIG_PATH);
    expect(r.reloadUrl).toBe(am.RELOAD_URL);
  });
});
