// Copyright [2026] [International Union of Railways (UIC)]
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//        http://www.apache.org/licenses/LICENSE-2.0

'use strict';

/**
 * alertmanagerConfig.js — render alertmanager.yml from OSCAR's Server Config
 * DB and reload the live Alertmanager process. Single source of truth for SMTP
 * across OSCAR and Alertmanager — admins maintain credentials in ONE place
 * (OSCAR's Server Config tab), this module propagates them.
 *
 * The generated YAML is written to ALERTMANAGER_CONFIG_PATH (env var, default
 * /etc/oscar-managed/alertmanager.yml). docker-compose.metrics.yml mounts the
 * same path inside the alertmanager container at /etc/alertmanager/alertmanager.yml.
 *
 * After write we POST to ALERTMANAGER_RELOAD_URL (default
 * http://alertmanager:9093/-/reload) to make the change effective without a
 * container restart. If the reload endpoint is unreachable (Alertmanager not
 * running, network blip), we still leave the file in place — the next
 * Alertmanager restart will pick it up.
 *
 * Returns { ok, written, reloaded, configPath, reloadStatus, reloadBody, error }
 * so the admin endpoint can surface the verbatim outcome to the UI.
 */

const fs   = require('fs');
const path = require('path');
const { getConfig } = require('../db/db');

// Defaults match the values shipped in the example file (and the production
// VPS layout). Both are env-overridable so dev / test deployments can point
// at different paths.
const CONFIG_PATH = process.env.ALERTMANAGER_CONFIG_PATH || '/etc/oscar-managed/alertmanager.yml';
const RELOAD_URL  = process.env.ALERTMANAGER_RELOAD_URL  || 'http://alertmanager:9093/-/reload';

/**
 * YAML scalar quoting — wraps in single quotes and escapes embedded single
 * quotes by doubling them (the YAML 1.2 escape rule for single-quoted scalars).
 * Safe for arbitrary user input — no template injection possible.
 */
function yq(s) {
  return "'" + String(s == null ? '' : s).replace(/'/g, "''") + "'";
}

/**
 * Split + clean a comma-separated email list. Drops empties, trims spaces,
 * lowercases. Does NOT validate addresses — Alertmanager will surface SMTP
 * errors at delivery time, which is more diagnostic than a regex here.
 */
function parseRecipients(raw) {
  return String(raw || '')
    .split(/[,;\n]/)
    .map(s => s.trim())
    .filter(Boolean);
}

/**
 * Build the full alertmanager.yml content string from current DB config.
 * Mirrors the structure of OSCAR_Deploy/alertmanager/alertmanager.yml.example
 * but driven entirely by Server Config values.
 */
function renderConfig() {
  const smtpHost   = getConfig('SMTP_HOST', '');
  const smtpPort   = getConfig('SMTP_PORT', '587');
  const smtpUser   = getConfig('SMTP_USER', '');
  const smtpPass   = getConfig('SMTP_PASS', '');
  const smtpFrom   = getConfig('SMTP_FROM', 'OSCAR Alerts <noreply@oscar.uic.org>');
  const smtpSecure = getConfig('SMTP_SECURE', 'false') === 'true';

  const recipients   = parseRecipients(getConfig('ALERT_RECIPIENTS', ''));
  const repeatCrit   = getConfig('ALERT_REPEAT_CRITICAL', '1h');
  const repeatWarn   = getConfig('ALERT_REPEAT_WARNING',  '4h');

  if (!smtpHost) throw new Error('SMTP_HOST is empty — set it on the Server Config tab before applying alerting config.');
  if (!recipients.length) throw new Error('ALERT_RECIPIENTS is empty — add at least one admin email on the Server Config tab.');

  const smarthost = `${smtpHost}:${smtpPort}`;
  // Alertmanager email_configs accepts a comma-separated list in a single
  // `to:` field — simpler than one entry per address (each entry would need
  // its own send_resolved + headers block to behave the same).
  const recipientsList = recipients.join(', ');

  // smtp_require_tls applies to STARTTLS upgrade (most common, port 587).
  // smtp_hello defaults to 'localhost' which Brevo etc. accept.
  // We do NOT set smtp_secure (Alertmanager doesn't have an analogous flag —
  // implicit TLS is selected by port 465 in the smarthost; STARTTLS is the
  // default everywhere else).
  const yaml = `# Auto-generated by OSCAR (do not edit by hand — changes will be overwritten).
# Source of truth: Server Config tab → SMTP + Alerting sections.
# Regenerated whenever an admin saves alerting settings or hits "Apply alerting config".

global:
  resolve_timeout: 5m
  smtp_smarthost:     ${yq(smarthost)}
  smtp_from:          ${yq(smtpFrom)}
  smtp_auth_username: ${yq(smtpUser)}
  smtp_auth_password: ${yq(smtpPass)}
  smtp_require_tls:   ${smtpSecure ? 'false' : 'true'}

route:
  receiver: oscar-admins
  group_by: ['alertname', 'severity']
  group_wait:      30s
  group_interval:  5m
  repeat_interval: ${yq(repeatWarn)}
  routes:
    - matchers:
        - severity = "critical"
      receiver: oscar-admins
      repeat_interval: ${yq(repeatCrit)}

receivers:
  - name: oscar-admins
    email_configs:
      - to: ${yq(recipientsList)}
        send_resolved: true
        headers:
          Subject: '[OSCAR {{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'

inhibit_rules:
  - source_matchers:
      - alertname = "OscarServerDown"
    target_matchers:
      - severity = "warning"
    equal: ['service']
`;

  return yaml;
}

/**
 * Write the rendered YAML to ALERTMANAGER_CONFIG_PATH. Creates parent dirs
 * as needed. Throws on any I/O failure so the caller can surface the
 * filesystem error verbatim (typically "permission denied" when the volume
 * isn't mounted RW, or "no such file or directory" when the volume isn't
 * mounted at all).
 */
function writeConfig(yaml) {
  const dir = path.dirname(CONFIG_PATH);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(CONFIG_PATH, yaml, { encoding: 'utf8', mode: 0o644 });
}

/**
 * Hit Alertmanager's built-in /-/reload endpoint. Returns { ok, status, body }.
 * Never throws — caller decides whether the reload-failure path is fatal.
 * Uses Node 22's built-in fetch with a 5-second timeout so a missing
 * Alertmanager doesn't hang the admin request.
 */
async function reload() {
  try {
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), 5000);
    const res = await fetch(RELOAD_URL, { method: 'POST', signal: ctrl.signal });
    clearTimeout(timer);
    const body = await res.text();
    return { ok: res.ok, status: res.status, body };
  } catch (err) {
    return { ok: false, status: 0, body: String(err && err.message || err) };
  }
}

/**
 * Top-level helper — render + write + reload. Captures every step's outcome
 * so the admin UI can show the user exactly what happened (and what to
 * do if any step partially fails).
 */
async function applyConfig() {
  const out = {
    ok: false,
    written: false,
    reloaded: false,
    configPath: CONFIG_PATH,
    reloadUrl:  RELOAD_URL,
    reloadStatus: null,
    reloadBody: null,
    error: null
  };

  let yaml;
  try { yaml = renderConfig(); }
  catch (err) { out.error = err.message; return out; }

  try { writeConfig(yaml); out.written = true; }
  catch (err) {
    out.error = `Could not write ${CONFIG_PATH}: ${err.message}. Make sure the alertmanager-config volume is mounted RW into the OSCAR container.`;
    return out;
  }

  const r = await reload();
  out.reloadStatus = r.status;
  out.reloadBody   = r.body;
  out.reloaded     = r.ok;
  out.ok           = r.ok;  // overall success only if reload landed
  if (!r.ok) {
    out.error = `Wrote ${CONFIG_PATH} successfully, but Alertmanager reload at ${RELOAD_URL} returned ${r.status || 'no response'}: ${r.body}. The new config will take effect on the next Alertmanager restart.`;
  }
  return out;
}

module.exports = {
  renderConfig,
  writeConfig,
  reload,
  applyConfig,
  CONFIG_PATH,
  RELOAD_URL,
};
